/** Configuración central del sitio (SEO, OG, sitemap). */
export const siteConfig = {
  name: "Reto ICFES",
  shortName: "Reto ICFES",
  domain: "retoicfes.com",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://retoicfes.com",
  description:
    "Simulacro Saber 11 gratis para grado 11° en Colombia. Rondas de 15 preguntas (3 por área): Matemáticas, Lectura Crítica, Sociales, Ciencias e Inglés, con retos rápidos y ranking por colegio.",
  keywords: [
    "ICFES",
    "Saber 11",
    "simulacro Saber 11",
    "simulacro ICFES",
    "prueba Saber 11",
    "grado 11",
    "bachillerato Colombia",
    "preparación ICFES",
    "preparación Saber 11",
    "preguntas tipo ICFES",
    "práctica ICFES gratis",
    "reto icfes",
    "reto ICFES",
    "ranking colegios Colombia",
    "examen grado 11",
    "pruebas de estado Colombia",
  ],
  locale: "es_CO",
  twitter: "@retoicfes",
  creator: "Reto ICFES",
} as const;
